### model
model_name_or_path: /Users/bytedance/项目/后训练工具/models/models/Qwen/Qwen2___5-0___5B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all

### dataset
dataset: identity
dataset_dir: /Users/bytedance/项目/后训练工具/LLaMA-Factory/data
template: qwen
cutoff_len: 1024
overwrite_cache: true
preprocessing_num_workers: 1
dataloader_num_workers: 0

### output
output_dir: /Users/bytedance/项目/后训练工具/m0_output
logging_steps: 5
save_steps: 1000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 1.0e-4
num_train_epochs: 30.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: false
fp16: false
